repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: .bumpversion.cfg
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix"]
      exclude: slack.json
- repo: git://github.com/detailyang/pre-commit-shell
  rev: 1.0.4
  hooks:
    - id: shell-lint
#-   repo: git://github.com/willthames/ansible-lint
#    sha: v3.4.16
#    hooks:
#    - id: ansible-lint
#      files: \.(yaml|yml)$
