---

- hosts: localhost
  become: no

  tasks:

    - name: Check for compatible Ansible version
      when: >
        ansible_version["string"] is version_compare("2.2", "<")
        or ansible_version["string"] is version_compare("2.9", ">=")
      fail:
        msg: >
          Your version of Ansible doesn't match the required version. Please
          install ansible-playbook with `pip install -r requirements.txt`.

- hosts: managed
  become: yes

  tasks:

    - name: Gather information from target server
      setup:

    - name: Check minimum CPU requirements
      fail:
        msg: "You need at least 2 vCPUs available, found {{ ansible_processor_vcpus }}"
      when: ansible_processor_vcpus < 2

    - name: Check minimum memory requirements
      fail:
        msg: "You need at least 8 Gb of memory available, found {{ ansible_memtotal_mb / 1024 }} Gb"
      when: ansible_memtotal_mb < 7500 and 'df' in mip_building_blocks

    - name: Check minimum memory requirements - without Data Factory
      fail:
        msg: "You need at least 4 Gb of memory available, found {{ ansible_memtotal_mb / 1024 }} Gb"
      when: ansible_memtotal_mb < 4000 and not 'df' in mip_building_blocks

    - name: Suggested target server hostname
      debug:
        msg: "Use {{ ansible_hostname }}"

    - name: Test reachability to suggested target server FQDN
      command: >
        ping -c 5 {{ ansible_fqdn }}
      ignore_errors: yes
      register: ansible_fqdn_check

    - name: Suggested target server FQDN
      debug:
        msg: "Use {{ ansible_fqdn }}"
      when: ansible_fqdn_check is success

    - name: Suggested target server FQDN
      debug:
        msg: "Use {{ ansible_default_ipv4.address }}"
      when: ansible_fqdn_check is failed

    - name: Suggested target server IP address
      debug:
        msg: "Use {{ ansible_default_ipv4.address }}"

- hosts: localhost
  become: no
  vars_prompt:
    - name: "server_hostname"
      prompt: "Target server hostname, e.g. myserver. Insert here the suggested target server hostname value displayed above"
      private: no
    - name: "server_fqdn"
      prompt: "Target server FQDN, e.g. myserver.myorg.com. Insert here the suggested target server FQDN value displayed above. It can be a DNS name or an IP address, it must be reachable from the installation computer and from the target servers"
      private: no
    - name: "server_ip_address"
      prompt: "Target server IP address. Insert here the suggested target server IP address"
      private: no
    - name: "portal_frontend_base_url"
      prompt: "Base URL for the frontend, for example https://myserver.myorg.com"
      private: no
    - name: "only_research_data"
      prompt: "Use research data only? (Y/n)"
      private: no

  roles:

    - role: mip-local
