---

# Sample advanced CircleCI configuration: https://github.com/transcom/mymove/blob/master/.circleci/config.yml

version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: hbpmip/docker-compose-for-ci:18.09-5
    environment:
       - CIRCLECI: true
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-$CACHE_VERSION-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: "Initialise Git submodules and Git hooks"
          command: |
            ./after-git-clone.sh
            ./after-update.sh
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-CACHE_VERSION-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run:
          name: "Test setup"
          command: |
            ./common/scripts/bootstrap.sh --skip-git-crypt
