---

- hosts: airflow-agent
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/data-factory/endpoints.yml"
    - "{{ play_dir }}/vars/data-factory/airflow.yml"

  vars:
    # Allow Airflow to run Docker containers
    airflow_user_groups: 'docker'

  pre_tasks:

    - name: Create group for Data factory user
      group:
        name: '{{ data_factory_group }}'
        gid: '{{ data_factory_group_id | default(omit)}}'
        state: present
      tags: ['spm', 'airflow-agent', 'airflow', 'data-factory']

    - name: Create user for Data Factory
      user:
        name: '{{ data_factory_user }}'
        uid: '{{ data_factory_user_id | default(omit)}}'
        group: '{{ data_factory_group }}'
        groups: '{{ data_factory_user_groups | default(omit)}}'
        home: "{{ data_factory_home | default('/usr/local/airflow') }}"
      tags: ['spm', 'airflow-agent', 'airflow', 'data-factory']
      when: airflow_user != 'vagrant'

  roles:

    - role: spm
      tags: ['spm', 'airflow-agent', 'airflow', 'data-factory', 'marathon-app']

    - role: airflow
      airflow_install_master: false
      airflow_install_agent: true
      tags: ['airflow-agent', 'airflow', 'data-factory', 'marathon-app']

    - role: audit-deployment
      installed_component: data-factory-airflow-agent
      tags: ['airflow', 'data-factory', 'marathon-app']
