---

# Version of the Docker image for woken to use
woken_validation_version: latest

# Id of woken in Marathon
woken_validation_marathon_id: /algorithm-factory/woken-validation

woken_validation_host: "{{ ansible_fqdn }}"
# Port for the HTTP api.
woken_validation_http_port: "31081"
# Port used by Akka cluster.
woken_validation_akka_port: "31082"
# Amount of CPU reserved for woken validation
woken_validation_cpus: 0.5
# Amount of memory in mb reserved for woken validation
woken_validation_mem: 1024.0
# Additional parameters for Docker
woken_validation_docker_parameters: []
woken_validation_docker_image_basename: hbpmip/woken-validation
woken_validation_docker_image: "{{ woken_validation_docker_image_basename }}:{{ woken_validation_version }}"

# Name of the bridge network to connect to. Used also for the communication of Docker algorithms launched via Chronos
woken_docker_bridge_network: 'bridge'

woken_validation_env:
  CLUSTER_PORT: "{{ woken_validation_akka_port }}"
  CLUSTER_IP: "{{ woken_validation_host }}"
  WOKEN_PORT_8088_TCP_ADDR: "{{ woken_host }}"
  WOKEN_PORT_8088_TCP_PORT: "{{ woken_akka_port }}"
  DOCKER_BRIDGE_NETWORK: "{{ woken_docker_bridge_network }}"
  LOG_LEVEL: DEBUG
  RELEASE_STAGE: "{{ release_stage | default('testing') }}"
  DATACENTER_LOCATION: "{{ woken_validation_marathon_host }}{% if mip_instance_name is defined and mip_instance_name %} at {{ mip_instance_name }}{% endif %}"

# Attach woken validation application to a particular host. The hostname should be the name known by Marathon / Mesos
woken_validation_marathon_host: "{{ ansible_fqdn }}"
# Set of constraints to use to place woken on some particular host(s)
woken_validation_marathon_constraints: [["hostname", "CLUSTER", "{{ woken_validation_marathon_host | trim }}"]]

woken_marathon_id: /algorithm-factory/woken
woken_validation_dependencies:
  - "{{ woken_marathon_id }}"

# URL to Marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: "http://{{ marathon_hostname }}:{{ marathon_port }}"
