---

#
# Setup both mesos-leader and mesos-follower on one or several servers.
# Requires: zookeeper installed on the same or some other servers.
#
# The following components are optional:
# * docker: use --skip-tags=docker
# * docker-registry-slave: use --skip-tags=docker-registry-slave or do not define
#       the variable docker_registry_config_orig_dir
#

- hosts: mesos-follower
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"

  pre_tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined
      tags: ['mesos', 'docker', 'os-tools', 'container-platforms', 'infra', 'infrastructure']

    - name: Check mesos_zk_hosts
      fail:
        msg: "Configuration variable mesos_zk_hosts should not contain 'localhost', value was {{ mesos_zk_hosts }}"
      when: mesos_zk_hosts is search('localhost')

  roles:

    - role: docker
      when: "'docker' not in skipped_roles"
      tags: ['docker', 'os-tools', 'container-platforms', 'infra', 'infrastructure']

#    - role: docker-registry-slave
#      tags: ['os-tools', 'container-platforms', 'docker', 'docker-registry-slave']
#      when: "'docker' not in skipped_roles and docker_registry_config_orig_dir is defined"

    - role: mesos
      zookeeper_hostnames: "{{ groups.zookeeper | join(',') }}"
      mesos_mode: "follower"
      mesos_leaders_group: "mesos-follower"
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']

    - role: audit-deployment
      installed_component: infrastructure-mesos-follower
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']
