---

#
# Setup both mesos-leader and mesos-follower on one or several servers.
# Requires: zookeeper installed on the same or some other servers.
#
# The following components are optional:
# * docker: use --skip-tags=docker
# * docker-registry-slave: use --skip-tags=docker-registry-slave or do not define
#       the variable docker_registry_config_orig_dir
# * marathon: use --skip-tags=marathon
# * mesos-ui: use --skip-tags=mesos-ui
#

- hosts: mesos-mixed
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"

  pre_tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']

    - name: Check mesos_zk_hosts
      fail:
        msg: "Configuration variable mesos_zk_hosts should not contain 'localhost', value was {{ mesos_zk_hosts }}"
      when: mesos_zk_hosts is search('localhost')


  roles:

    - role: docker
      when: "'docker' not in skipped_roles"
      tags: ['docker', 'os-tools', 'container-platforms', 'infra', 'infrastructure']

#    - role: docker-registry-slave
#      tags: ['os-tools', 'container-platforms', 'docker', 'docker-registry-slave']
#      when: "'docker' not in skipped_roles and docker_registry_config_orig_dir is defined"

    - role: mesos
      mesos_mode: "mixed"
      mesos_leaders_group: "mesos-mixed"
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']

    # Java 8 is required for Marathon
    - role: openjdk
      when: "'marathon' not in skipped_roles"
      tags: ['openjdk', 'marathon', 'mesos-frameworks', 'runtimes', 'infra', 'infrastructure']

    # TODO: should install only Marathon on 1 server, or deal with HA config for Marathon
    - role: marathon
      when: "'marathon' not in skipped_roles"
      tags: ['marathon', 'mesos-frameworks', 'runtimes', 'infra', 'infrastructure']

    #- role: mesos-ui
    #  tags: ['mesos-frameworks', 'mesos-ui']
    #  when: "'mesos-ui' not in skipped_roles"

    - role: audit-deployment
      installed_component: infrastructure-mesos-mixed
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']
